spring:
  application:
    name: Welcome-API
  # Admin Client config
  boot:
    admin:
      client:
        url: http://localhost:1111/
# If your erueka is running on any other port than 8761, like 9090
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9090/eureka
# Exposing all endpoints to actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'